/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jiage_jnilogdemo_MainActivity */

#ifndef _Included_com_jiage_jnilogdemo_MainActivity
#define _Included_com_jiage_jnilogdemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jiage_jnilogdemo_MainActivity
 * Method:    getCString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jiage_jnilogdemo_MainActivity_getCString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
