/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jiage_jniccalljava_Utils */

#ifndef _Included_com_jiage_jniccalljava_Utils
#define _Included_com_jiage_jniccalljava_Utils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jiage_jniccalljava_Utils
 * Method:    callC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jiage_jniccalljava_Utils_callC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
