/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jiage_jnidynamicregister_DynamicUtils */

#ifndef _Included_com_jiage_jnidynamicregister_DynamicUtils
#define _Included_com_jiage_jnidynamicregister_DynamicUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jiage_jnidynamicregister_DynamicUtils
 * Method:    getString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jiage_jnidynamicregister_DynamicUtils_getString
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
