/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jiage_jniencode_CodeUtil */

#ifndef _Included_com_jiage_jniencode_CodeUtil
#define _Included_com_jiage_jniencode_CodeUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jiage_jniencode_CodeUtil
 * Method:    encode
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jiage_jniencode_CodeUtil_encode
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jiage_jniencode_CodeUtil
 * Method:    decode
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jiage_jniencode_CodeUtil_decode
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
