/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jiage_jnindkbuild_Native */

#ifndef _Included_com_jiage_jnindkbuild_Native
#define _Included_com_jiage_jnindkbuild_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jiage_jnindkbuild_Native
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jiage_jnindkbuild_Native_getString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
