/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jiage_demo_JNIUtil */

#ifndef _Included_com_jiage_demo_JNIUtil
#define _Included_com_jiage_demo_JNIUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jiage_demo_JNIUtil
 * Method:    getStr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jiage_demo_JNIUtil_getStr
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jiage_demo_JNIUtil
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jiage_demo_JNIUtil_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_jiage_demo_JNIUtil
 * Method:    transmitArray
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_jiage_demo_JNIUtil_transmitArray
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
